protected/controllers/DocController.php
<?php

class DocController extends GxController
{

    var $user;
	
	var $transferFrom;

    public function init()
    {
        $this->user = User::model()->findByPk(Yii::app()->user->id);
    }

	/**
	 * @return array action filters
	 */
    public function filters()
    {
        return array(
            'accessControl',
        );
    }

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
    public function accessRules()
    {
        if ($this->user !== null && $this->user->approved == TRUE)
        {
            // approved
            $userId = $this->user->user_id;
        }
        else
        {
            // not approved
            $userId = 'notapproved';
        }
		// check admin user
        $adminUser = (Yii::app()->params->adminId == $userId)? 'true':'false';
        $dataManager = ($this->user->data_manager == true)? 'true':'false';
		return array(
			array('allow', 
				'actions'=>array('index','view','active','inactive','resync','create','update','admin','transfer','fail','export'),
				'expression' => "$adminUser || $dataManager",
			),
			array('allow', 
				'actions'=>array('index','view'),
				'users'=>array('@'),
			),
			array('deny', 
				'users'=>array('*'),
			),
		);
    }

	/**
	 * Displays a particular document model.
	 * @param integer $id the ID of the model to be displayed
	 */
    public function actionView($id)
	{
		$model = $this->loadModel($id, 'Doc');
		
		if (($this->user->user_id != $model->user_id) && (Yii::app()->params->adminId !== $this->user->user_id))
		{
			$this->redirect(array('index'));
		}
		else
		{
			$xml = simplexml_load_string($model->doc_xml);
			$doc_array = Array2XML::createArray($xml, TRUE, FALSE, TRUE);

			$temp = DataCite2_2::deconstructDataArray($model, $doc_array);
			$this->render('view', array(
				'model' => $model,
			));
		}
	}

	/**
	 * Export DOI to TXT actions.
	 * 
	 */
    public function actionExport()
    {
    
       // header("Content-type: application/txt");
       // header('Content-disposition: filename="TERN-DOI.txt"');

	 $criteria = '';
        $criteria .= (isset($_GET['Doc']['doc_title']) && $_GET['Doc']['doc_title'])? ' AND doc_title like \'%'.$_GET['Doc']['doc_title'].'%\'':''; 
        $criteria .= (isset($_GET['Doc']['doc_url']) && $_GET['Doc']['doc_url'])? ' AND doc_url like \'%'.$_GET['Doc']['doc_url'].'%\'':''; 
        $criteria .= (isset($_GET['Doc']['doc_doi']) && $_GET['Doc']['doc_doi'])? ' AND doc_doi like \'%'.$_GET['Doc']['doc_doi'].'%\'':''; 
        $criteria .= (isset($_GET['Doc']['user_id']) && $_GET['Doc']['user_id'])? ' AND user_id like \'%'.$_GET['Doc']['user_id'].'%\'':''; 
        $sql = 'select * from tbl_doc where doc_doi != \'\'' . $criteria;

        $model = Doc::model()->findAllBySql($sql);
        print_r($model);die();        
        $doiArray = array();
        $citationArray = array();
        for ($c=0;$c<count($model);$c++)
        {
            $xml = simplexml_load_string($model[$c]->doc_xml);
            $doc_array = Array2XML::createArray($xml, TRUE, FALSE, TRUE);
            $temp = DataCite2_2::deconstructDataArray($model[$c], $doc_array);
            $doiArray[$c] = $model[$c]->publicationYear;
            $citationArray[$c] = strip_tags ( dataCitate(Array('creator' => $model[$c]->creator, 'publicationYear' => $model[$c]->publicationYear, 'title' => $model[$c]->doc_title, 'publisher' => $model[$c]->publisher, 'identifier' => $model[$c]->doc_doi)));
        }

        asort($doiArray); 

        foreach ($doiArray as $key => $year) {
            echo "$citationArray[$key]\r\n";
        }
    }

	/**
	 * Displays fail page for mint and update actions.
	 * 
	 */
    public function actionFail($id)
	{
		$this->render('fail', array('id'=>$id));
	}


	/**
	 * Activate a particular document model.
	 * @param integer $id the ID of the model to be activated
	 */
    public function actionActive($id)
	{
		$model = $this->loadModel($id, 'Doc');
		$cite = new CiteANDS();
		// check document status and process if it is not a new unminted document
		if($model->doc_status != 'new')
		{
			// activate document
			$doi = $cite->getANDS($model->doc_doi,  'activate');
			if ($doi['doi'] != '')
			{
				 $model->doc_active = true;
				 $model->saveAttributes(array('doc_active'));
				 Yii::app()->user->setFlash('success','Activated Successfully');
			} 
			else 
			{
				Yii::app()->user->setFlash('error','Failed activating DOI');
			}
		}
		else{
			Yii::app()->user->setFlash('error','This DOI has not been minted. Please synchronise the data first');
		}
		$this->redirect(array('admin'));
	}
	
	/**
	 * Deactivate a particular document model.
	 * @param integer $id the ID of the model to be deactivated
	 */
    public function actionInactive($id)
	{
		$model = $this->loadModel($id, 'Doc');
		$cite = new CiteANDS();
		// check document status and process if it is not a new unminted document
		if($model->doc_status != 'new')
		{
			// deactivate document
			$doi = $cite->getANDS($model->doc_doi,  'deactivate');
			if ($doi['doi'] != '')
			{
				$model->doc_active = false;
				$model->saveAttributes(array('doc_active'));
				Yii::app()->user->setFlash('success','Deactivated Successfully');
			} 
			else
			{
				Yii::app()->user->setFlash('error','Failed deactivating DOI');
			}
		}
		$this->redirect(array('admin'));
	}

	/**
	 * Deactivate a particular document model.
	 * @param integer $id the ID of the model to be minted or updated
	 */
    public function actionResync($id)
	{
		$model = $this->loadModel($id, 'Doc');
		$cite = new CiteANDS();
		// check document status
		if($model->doc_doi)
		{
			$doi = $cite->postANDS($model->doc_url, $model->doc_xml, 'update', $model->doc_doi);
			if ($doi['doi'] != '' && $doi['response']['type']!='failure')
			{
				$model->doc_status = 'Successfully minted';
				$model->doc_active = true;
				$model->saveAttributes(array('doc_status', 'doc_active'));
				Yii::app()->user->setFlash('success','Synchronized Successfully');
			}
			else
			{
				$status = $doi['xml'];
				Yii::app()->user->setFlash('error','Synchronize unsuccessful:'.$status);
			}
		}
		else
		{
			$doi = $cite->postANDS($model->doc_url, $model->doc_xml, 'mint');

			if ($doi['doi'] != '' && $doi['response']['type']!='failure')
			{
				$model->doc_doi = $doi['doi'];
				$model->doc_status = 'Successfully minted';
				$model->doc_active = true;
				$model->saveAttributes(array('doc_doi', 'doc_status', 'doc_active'));
				Yii::app()->user->setFlash('success','Synchronized Successfully');
			}
			else
			{
				$status = $doi['xml'];
				Yii::app()->user->setFlash('error','Synchronize unsuccessful:'.$status);
			}
		}

		//return to the Admin Page
		$model = new Doc('search');
		$model->unsetAttributes();

		if (isset($_GET['Doc']))
			$model->setAttributes($_GET['Doc']);
		$this->redirect(array('admin'));
	}

	/**
	 * Mint a particular document model.
	 */
    public function actionCreate()
	{
		$model = new Doc;
		$user = $this->user;
                
               
		if (isset($_POST['Doc']))
		{
			$model->setAttributes($_POST['Doc']);
                        
			if ($model->save())
			{
                            //print_r($model);die();
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
                                    
					if (($model->doc_doi && $model->doc_status == 'Successfully minted') || $model->doc_status == 'new' || $model->doc_status == 'updated')
					{
						$this->redirect(array('view', 'id' => $model->doc_id));
					}
					else
					{
						$this->redirect(array('fail', 'id' => $model->doc_id));
					}
			}
		}

		$this->render('create', array('model' => $model));
	}

	/**
	 * Update a particular document model.
	 * @param integer $id the ID of the model to be updated
	 */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id, 'Doc');
     
        $xml = simplexml_load_string($model->doc_xml);
        $doc_array = Array2XML::createArray($xml, TRUE, FALSE, TRUE);
        DataCite2_2::deconstructDataArray($model, $doc_array);

        if (isset($_POST['Doc']))
        {
            $model->setAttributes($_POST['Doc']);
            if ($model->save())
            {
				if (($model->doc_doi && $model->doc_status == 'Successfully minted') || $model->doc_status == 'new' || $model->doc_status == 'updated')
				{
					$this->redirect(array('view', 'id' => $model->doc_id));
				}
				else
				{
					$this->redirect(array('fail', 'id' => $model->doc_id));
				}
            }
        }
        $this->render('update', array(
            'model' => $model,
        ));
    }

	/**
	 * Lists all minted document owned by the user.
	 */
    public function actionIndex()
    {
        if ($this->user !== null && $this->user->approved == TRUE)
        {
            // approved
            $userId = $this->user->email;
        }
        else
        {
            // not approved
            $userId = 'notapproved';
        }
        $model=new Doc('search');
        $model->unsetAttributes(); 
        if(isset($_GET['Doc']))
	 {
            $model->attributes=$_GET['Doc'];
            $model->user_id=$_GET['Doc']['user_id'];
        }
        else
        {
            $model->doc_doi='index page';
        }
        $this->render('index',array(
            'dataProvider'=>$model->search(),
            'model'=>$model)
        ); 

    }

	/**
	 * Manages all documents.
	 */
    public function actionAdmin()
	{
		$model = new Doc('search');
		$model->unsetAttributes();
		if (isset($_GET['Doc']))
			$model->setAttributes($_GET['Doc']);

		if (Yii::app()->params->adminId != $this->user->email)
		{
              	$model->user_id=$this->user->email;
		}

		$this->render('admin', array(
			'model' => $model,
		));
	}

	/**
	 * Transfer DOIs between Data Manager.
	 */
	public function actionTransfer($id)
    {

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
var $user;

public function init(){
       
       $this->user = User::model()->findByPk(Yii::app()->user->id);
       
}
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		if($this->user !== null && $this->user->approved == TRUE && $this->user->enabled==TRUE)
                {
                    // approved
                    $userId= $this->user->user_id;
                }
		else
		{
                    // not approved
                    $userId= 'notapproved';
                }
		// check admin user
                $adminUser = (Yii::app()->params->adminId == $userId)? true:false;
		return array(
			array('allow', 
				'actions'=>array('index','update','create','enabled','disabled','admin'),
				'expression' => "$adminUser",
			),
			array('allow', 
				'actions'=>array('index','update','view'),
				'users'=>array('@'),
			),
			array('deny', 
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		if (!(Yii::app()->params->adminId == Yii::app()->user->id || 
			Yii::app()->user->id == $id))
		{
			$this->redirect(array('index'));
		}
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			$model->facility=$_POST['fac'];
			//$model->approved=$_POST['app'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->user_id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates the USER model.
	 * If not updated by administrator then set approved = false and send an email to administrator  
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{            
		if (!(Yii::app()->params->adminId == Yii::app()->user->id || 
			Yii::app()->user->id == $id))
		{
			$this->redirect(array('index'));
		}
		$model=$this->loadModel($id);
		$facilities = explode('<br/>', $model->facility);
		$facilityArray = null;
		for ($i=0; $i< count($facilities); $i++)
		{
			$facilityArray[$i]['@value'] = $facilities[$i];
		}
		$model->facility = $facilityArray; 

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$facilities = null;
			foreach ($_POST['User']['facility'] as &$facility) 
			{
				if (!strpos($facilities, $facility['@value']))
				{
					$facilities .= '<br/>'.$facility['@value'] ;
				}
			}
			$_POST['User']['facility'] = subStr($facilities, 5); 

			$model->attributes=$_POST['User'];

			$checkChange=User::model()->findByAttributes(array('user_id'=>$_GET['id'],'facility'=>$_POST['User']['facility'],'data_manager'=>$_POST['User']['data_manager'],'appid_seed'=>$_POST['User']['appid_seed'],'approved'=>$_POST['User']['approved']));
			if ($checkChange){
				$this->redirect(Yii::app()->user->returnUrl.'?r=user/index');
			}			


			if (Yii::app()->params->adminId != $this->user->user_id)
			{
				mailAdmin($model);
				$model->approved = false;
			}
			else if ((Yii::app()->params->adminId == $this->user->user_id) && ($model->approved == true)) 
			{
				mailUser($model);
			}
							
			if($model->save())
			{
				if (Yii::app()->params->adminId == $this->user->user_id)
				{
					$this->redirect(array('admin'));
				} 
				elseif ($model->approved == FALSE)
				{
	           			$this->redirect(Yii::app()->user->returnUrl.'?r=site/notapproved');
				}
				else				
				{
					$this->redirect(array('index','id'=>Yii::app()->user->id));
				}
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
/*	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id,'User')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
                $this->redirect(array('admin'));
			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}*/

	/**
	 * Display the user profile.
	 */
	public function actionIndex()
	{
		/*
			$dataProvider=new CActiveDataProvider('User');
			$this->render('index',array(
				'dataProvider'=>$dataProvider,
			));
			*/
		if($this->user !== null && $this->user->approved == TRUE && $this->user->enabled==TRUE)
                {
                    // approved
                    $userId= $this->user->user_id;
                }
		else
		{
                    // not approved
                    $userId= 'notapproved';
                }

        $dataProvider = new CActiveDataProvider('User', array(
                    'criteria' => array(
                        'condition' => 'user_id=:user_val ',
                        'params' => array(':user_val' => $userId)
                    ),
                        )
        );

        $this->render('index', array(
            'dataProvider' => $dataProvider
                )
        );
		
	}

	/**
	 * Manages all users.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	/**
	 * Enable selected user.
	 */
	public function actionEnabled($id)
    {
          $model = $this->loadModel($id, 'User');
			
          $model->enabled=true;
          $model->save();
          
          $this->redirect(array('admin'));
    }

	/**
	 * Disable selected user.
	 */
	public function actionDisabled($id)
    {
          $model = $this->loadModel($id, 'User');
         
          $model->enabled=false;
          $model->save();
          $this->redirect(array('admin'));

    }

}

protected/views/doc/_admin.php
<?php

$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'doc-grid',
    'dataProvider' => $dataProvider,
    //'filter' => $model,
    'columns' => array(
        array(
            'name' => 'Title',
            'value' => 'CHtml::link(GxHtml::encode($data->doc_title), array("doc/view", "id" => $data->doc_id))',
            'type' => 'raw',
        ),
        'doc_url',
        'doc_status',
        'doc_doi',
    ),
));
?>

protected/views/doc/_search.php
<div class="wide form">

<?php
if ($model['doc_doi']=='index page'){
	$model['doc_doi']='';
}

$form = $this->beginWidget('GxActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>



	<div class="row">
		<?php echo $form->label($model, 'doc_title'); ?>
		<?php echo $form->textField($model, 'doc_title', array('maxlength' => 128)); ?>
	</div>
	<div class="row">
		<?php echo $form->label($model, 'doc_url'); ?>
		<?php echo $form->textField($model, 'doc_url', array('maxlength' => 256)); ?>
	</div>
	<div class="row">
		<?php echo $form->label($model, 'doc_doi'); ?>
		<?php echo $form->textField($model, 'doc_doi', array('maxlength' => 128)); ?>
	</div>
	<div class="row">
		<?php echo $form->label($model, 'user_id'); ?>
		<?php echo $form->textField($model, 'user_id', array('maxlength' => 256)); ?>
		<span class="inputTitle" id="hdatamgr"><img src="<?php echo Yii::app()->theme->baseUrl . '/images/help.png'; ?>"></span>
		<div class="help" id="help-hdatamgr">Data manager can be refined by email id only.</div>
	</div>

	<div class="row buttons">
		<?php echo GxHtml::submitButton(Yii::t('app', 'Search')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/doc/_view.php
<div class="view">

	<!--?php echo GxHtml::encode($data->getAttributeLabel('doc_id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->doc_id), array('view', 'id' => $data->doc_id)); ?>
	<br /-->
	<strong>Title:</strong> 
	<?php
		if ($this->user->user_id == $data->user_id)
		{
			echo GxHtml::link(GxHtml::encode($data->doc_title), array('view', 'id' => $data->doc_id)); 
		}
		else
		{
			echo GxHtml::encode($data->doc_title); 
		}
	?>
	<br />
	<strong><?php echo GxHtml::encode($data->getAttributeLabel('doc_url')); ?>: </strong><?php echo GxHtml::encode($data->doc_url); ?><br />
	<strong><?php echo GxHtml::encode($data->getAttributeLabel('doc_doi')); ?>: </strong><?php echo GxHtml::encode($data->doc_doi); ?><br />
	<strong><?php echo GxHtml::encode($data->getAttributeLabel('user_id')); ?>: </strong><?php echo GxHtml::encode($data->user_id); ?><br />
</div>

protected/views/doc/admin.php
<?php
$this->breadcrumbs = array(
    $model->label(2) => array('index'),
    Yii::t('app', 'Manage'),
);

$this->menu = array(
    //	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
    array('label' => Yii::t('app', 'Create ') . ' ' . $model->label(), 'url' => array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('doc-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo Yii::t('app', 'Manage') . ' ' . GxHtml::encode($model->label(2)); ?></h1>


<?php /*echo GxHtml::link(Yii::t('app', 'Search'), '#', array('class' => 'search-button'));*/ ?>
<!--div class="search-form">
    <?php
//    $this->renderPartial('_search', array(
//        'model' => $model,
//    ));
    ?>
</div--><!-- search-form -->
<div id="statusMsg">
<?php if(Yii::app()->user->hasFlash('success')):?>
    <div class="flash-success">
        <?php echo Yii::app()->user->getFlash('success'); ?>
    </div>
<?php endif; ?>

<?php if(Yii::app()->user->hasFlash('error')):?>
    <div class="flash-error">
        <?php echo Yii::app()->user->getFlash('error'); ?>
    </div>
<?php endif; ?>
</div>
<?php
    $this->widget('zii.widgets.grid.CGridView', array(
        'id' => 'doc-grid',
        'dataProvider' => $model->search(),
        'filter' => $model,
        'columns' => array(
            'doc_title',
            'doc_url',
            array(
		'name' => 'doc_doi',
		'header' => 'DOI',
		'type' => 'raw',
		'value' => '($data->doc_doi)? str_replace(\'%D$s\',$data->doc_doi,substr(Yii::app()->params->doiCitateFormat,strpos(Yii::app()->params->doiCitateFormat,"<a"))):""',
            ),
            array(
                'header' => 'Metadata Sync Status',
                'class' => 'CButtonColumn',
                'template' => '{sync} {unsync}',
                'buttons' => array(
                    'sync' => array(
                        'label' => 'Is synchronized with ANDS',
                        'imageUrl' => Yii::app()->theme->baseUrl  . '/images/sync.png',
                         'visible' => '$data->doc_status == "Successfully minted"',
                    ),
                    'unsync' => array(
                        'label' => 'Click to synchronize with ANDS',
                        'imageUrl' => Yii::app()->theme->baseUrl  . '/images/unsync.png',
                        'url' => 'Yii::app()->createUrl("doc/resync",array("id"=>$data->doc_id))',
                        'ajax' => true,
                        'visible' => '$data->doc_status != "Successfully minted"',
                    ),
                ),
            ),
            array(
                'header' => 'Active Status',
                'class' => 'CButtonColumn',
                'template' => '{active} {inactive}',
                'buttons' => array(
                    'active' => array(
                        'label' => 'Click to deactivate DOI',
                        'imageUrl' => Yii::app()->theme->baseUrl  . '/images/go.png',
                        'url' => 'Yii::app()->createUrl("doc/inactive",array("id"=>$data->doc_id))',
                        'ajax' => true,
                        'visible' => '$data->doc_active == 1',
                    ),
                    'inactive' => array(
                        'label' => 'Click to activate DOI',
                        'imageUrl' =>  Yii::app()->theme->baseUrl  . '/images/stop.png',
                        'url' => 'Yii::app()->createUrl("doc/active",array("id"=>$data->doc_id))',
                        'ajax' => true,
                        'visible' => '$data->doc_active == 0',
                    ),
                ),
            ),
		array(
			'header' => 'Actions',
			'class' => 'CButtonColumn',
			'template' => ' {view} {update} ',
			'buttons' => array(
				'view' => array(
					'label'=>'View detail',
				),
				'update' => array(
					'label'=>'Update record',
				)
			)
            ),
        ),
    ));
?>

protected/views/doc/fail.php
<?php
$model = Doc::model()->findByPk($id);

if ($model->doc_status == 'Successfully minted')
{
    $title = 'Successfully minted';
    $class = 'flash-success';
}
else
{
    $title = 'Fail Minting';
    $class = 'flash-error';
}

$this->breadcrumbs = array(
    'DOIs' => array('index'),
    $title,
);

$this->menu = array(
    array('label' => Yii::t('app', 'Create DOI') , 'url' => array('create')),
    array('label' => Yii::t('app', 'Update DOI') , 'url' => array('update', 'id' => $id)),
    array('label' => Yii::t('app', 'Manage DOI') , 'url' => array('admin')),
);
?>

<h1><?= $title ?></h1>
<div class="<?= $class ?>">
<?= $model->doc_status ?>
</div>

protected/views/doc/transfer.php
<?php
$transferFrom = User::model()->findByPk($this->transferFrom);
$transferTo = User::model()->findAllbyAttributes(array('data_manager'=>true));
$transferToList = '<select id="transferTo" name="transferTo"><option></option>';
for ($i=0;$i<count($transferTo);$i++)
{
	$transferToList .= '<option value='.$transferTo[$i]->user_id.'>'.$transferTo[$i]->username.'</option>';
} 
$transferToList .= '</select>';

$this->breadcrumbs = array(
    $model->label(2) => array('index'),
    Yii::t('app', 'Transfer'),
);

$this->menu = array(
    array('label' => 'Manage Users', 'url' => array('user/admin')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('doc-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>
<script>
function actionTransfer()
{
	if (document.getElementById('transferTo').value != '')
	{
		document.transfer.submit();
	}
	else
	{
		alert('Please select a Data Manager for DOIs transfer.');
	}
}
</script>
<h3>Transfer DOIs from <?= $transferFrom->username ?></h3>
<form name="transfer" action="?r=doc/transfer&id=<?= $transferFrom->user_id?>" method="post">
<strong>To:</strong> <?= $transferToList ?>
<input type="button" onclick="actionTransfer();" name="Transfer" value="Transfer" />

<?php

    $this->widget('zii.widgets.grid.CGridView', array(
        'id' => 'doc-grid',
        'dataProvider' => $model->transfer($transferFrom->user_id),
        'filter' => $model,
        'columns' => array(
            'doc_title',
            'doc_url',
            'doc_doi',
            array(
                'header' => 'Select',
				'value'=>'CHtml::checkBox("doi[]","", array("value"=>$data->doc_doi))',
				'type'=>'raw',
				'htmlOptions'=>array('style'=>'text-align:center;'),
			),
        ),
    ));
?>
</form>