protected/controllers/SiteController.php
<?php
$baseP=Yii::app()->basePath;

require $baseP.'/include/openid.php';

class SiteController extends GxController
{
        private $_identity;
        /**
         * Declares class-based actions.
         */
        public function actions()
        {
                return array(
                        // captcha action renders the CAPTCHA image displayed on the contact page
                        'captcha'=>array(
                                'class'=>'CCaptchaAction',
                                'backColor'=>0xFFFFFF,
                        ),
                        // page action renders "static" pages stored under 'protected/views/site/pages'
                        // They can be accessed via: index.php?r=site/page&view=FileName
                        'page'=>array(
                                'class'=>'CViewAction',
                        ),
                );
        }

        /**
         * This is the default 'index' action that is invoked
         * when an action is not explicitly requested by users.
         */
        public function actionIndex()
        {
                // renders the view file 'protected/views/site/index.php'
                // using the default layout 'protected/views/layouts/main.php'
                $this->render('index');
        }

        /**
         * This is the action when user is not yet approved
         */
        public function actionNotapproved()
        {
                $this->render('notapproved');
        }

        /**
         * This is the action when user is disabled by administrator
         */
        public function actionNotenabled()
        {
                $this->render('notenabled');
        }

        /**
         * This is the action to handle external exceptions.
         */
        public function actionError()
        {
            //print_r(Yii::app()->errorHandler->error);die();
            if($error==Yii::app()->errorHandler->error)
            {
                if(Yii::app()->request->isAjaxRequest)
                        echo $error['message'];
                else
                        $this->render('error', $error);
            }
        }

        /**
         * Displays the contact page
         */
        public function actionContact()
        {
                $model=new ContactForm;
                if(isset($_POST['ContactForm']))
                {
                        $model->attributes=$_POST['ContactForm'];
                        if($model->validate())
                        {
                                $headers="From: {$model->email}\r\nReply-To: {$model->email}";
                                mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
                                Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
                                $this->refresh();
                        }
                }
                $this->render('contact',array('model'=>$model));
        }

        /**
         * Displays the login page
         */

        public function actionLogin()
        {

              $this->render('loginoption');

        }

        /**
         * Logs out the current user and redirect to homepage.
         */
        public function actionLogout()
        {
                Yii::app()->user->logout();
                $this->redirect(Yii::app()->homeUrl);
        }


        public function actionAAF()
        {
                $session_expiration = time() + 3600 * 24 * 2; // +2 days
                session_set_cookie_params($session_expiration);
                session_start();

               // print_r($_SESSION);die();
                $id = $_SESSION['email'];
                $email = $_SESSION['email'];
                $displayName = $_SESSION['displayName'];
                $organizationName = $_SESSION['organizationName'];

                if(isset($_SESSION['displayName']))
                {
                        Yii::app()->user->name = $displayName;
                        Yii::app()->user->id = $email;
                        $model=User::model()->findByPk($email);

                        if ($model!=null && $model->facility==''){
                                $this->loadModel($email,'User')->delete();
                                $model=null;
                        }

                        if($model!=null)
                        {
                                if($model->user_id==Yii::app()->params['adminId'])
                                {
                                        $model->username=Yii::app()->user->name;
                                        $model->approved=true;
                                        $model->enabled=true;
                                        $model->save(false);
                                        $this->redirect(Yii::app()->baseUrl . '/index.php?r=user/index');
                                }
                                else
                                {
                                        if($model->approved==true && $model->enabled==true)
                                        {
                                                $this->redirect(Yii::app()->baseUrl . '/index.php?r=doc/index');
                                        }
                                        else if($model->approved==false)
                                        {
                                                $this->redirect(Yii::app()->user->returnUrl.'?r=site/notapproved');
                                        }
                                        else
                                        {
                                                $this->redirect(Yii::app()->user->returnUrl.'?r=site/notenabled');
                                        }
                                }
                        }
                        else
                        {
                                $model=new User;
                                $model->email=$email;
                                $model->user_id=$email;
                                $model->username=Yii::app()->user->name;
                                $model->approved=false;
                                $model->enabled=true;
                                $model->save(false);
                                $this->render('createuser',array('model'=>$model));
                        }
                }
                else
                {
                        echo 'User has not logged in.';
                }

        }

        public function actionGoogle()
        {
                //$model=new User;
                try {

//              $openid = new LightOpenID('qcifvm2.genome.at.uq.edu.au');
                $openid = new LightOpenID('doi.nci.org.au');
                //$openid = new LightOpenID('localhost');
                if(!$openid->mode)
                {
 //                     if(isset($_GET['googlelogin']))
 //                     {
                        $openid->identity = 'https://www.google.com/accounts/o8/id';
                        $openid->required = array('namePerson/first', 'namePerson/last', 'contact/email');
                        header('Location: ' . $openid->authUrl());
                        } elseif($openid->mode == 'cancel') {
                                echo 'User has canceled authentication!';
                        }else {
                                if($openid->validate())
                                {
                                    //echo 'User <b>' . $openid->identity . '</b> has logged in.<br>';

                                    //echo "<h3>User information</h3>";

                                    $identity = $openid->identity;
                                    $attributes = $openid->getAttributes();
                                    $email = $attributes['contact/email'];
                                    $id = $attributes['contact/email'];

                                    if(isset($attributes['namePerson/first']))
                                    {
                                        $first_name = $attributes['namePerson/first'];
                                    }else
                                    {
                                        $first_name='';
                                    }
                                    if(isset($attributes['namePerson/last']))
                                    {
                                        $last_name = $attributes['namePerson/last'];
                                    }else
                                    {
                                        $last_name='';
                                    }


                                    if($first_name.$last_name!='')
                                    {
                                                        Yii::app()->user->name=$first_name.' '.$last_name;

                                    }else
                                    {
                                        Yii::app()->user->name=$email;
                                    }
                                                        //Yii::app()->user->name=$email;
                                                        Yii::app()->user->id=$email;

                                  //  print_r(Yii::app()->user->guestName);
                                  //  print_r(Yii::app()->user);
                                   // Yii::app()->user->login($email);

                                    //print_r(Yii::app()->user->name);

                                   // $model->id=$email;
                                    //$model->username=$first_name.' '.$last_name;

                                    $model=User::model()->findByPk($id);
                                    //$model->username=$first_name.' '.$last_name;

protected/views/site/contact.php
<?php
$this->pageTitle=Yii::app()->name . ' - Contact Us';
$this->breadcrumbs=array(
	'Contact',
);
?>

<h1>Contact Us</h1>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('contact'); ?>
</div>

<?php else: ?>

<p>
If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
</p>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'contact-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name'); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'subject'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'body'); ?>
		<?php echo $form->textArea($model,'body',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'body'); ?>
	</div>

	<?php if(CCaptcha::checkRequirements()): ?>
	<div class="row">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		<div>
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'verifyCode'); ?>
		</div>
		<div class="hint">Please enter the letters as they are shown in the image above.
		<br/>Letters are not case-sensitive.</div>
		<?php echo $form->error($model,'verifyCode'); ?>
	</div>
	<?php endif; ?>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php endif; ?>

protected/views/site/createuser.php
<?php Yii::app()->clientScript->registerCoreScript('jquery'); ?>
<?php Yii::app()->clientScript->registerCoreScript('jquery.ui');?>
<?php Yii::app()->clientScript->registerCssFile(
	Yii::app()->clientScript->getCoreScriptUrl().
	'/jui/css/base/jquery-ui.css'
);?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl . "/js/multifield.js"); ?>
<?php
$this->pageTitle=Yii::app()->name . ' - Register User';
$this->breadcrumbs=array(
	'Register User',
);
?>

<h1>Register User</h1>

<p>Please fill out the following form:</p>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'createUser-form',
	'enableClientValidation'=>true,
	'action'=>array('/site/createuser')

)); ?>

	<div class="row">
		<?php echo $form->label($model,'username'); ?>
		<?php echo $model->username; ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $model->user_id ?>
	</div>

	<div class="row">
		<table class="tableForm indent"  id="facilityRow">
			<tr>
				<th><?php echo $form->label($model,'facility'); ?></th>
				<th></th>
			</tr>
			<?php
			if (count($model->facility) == 0)
			{
				$c = 1;
			}
			else
			{
				$c = count($model->facility);
			}

			for ($i = 0; $i < $c; $i++)
			{
			?>
			<tr id="facilityTemplateRow" >
				<td>
					<?php echo CHtml::dropDownList('User[facility][0][@value]','auscover', Yii::app()->params->facilityList); ?>
				</td>
				<td>
					<?php
					if ($i == 0)
					{
						echo CHtml::htmlButton('+', array('onClick' => 'addRow(\'facility\')'));
					}
					else
					{
						echo CHtml::htmlButton('-', array('id' => 'DeleteBoxRow'));
					}
					?>
				 </td>
			 </tr>
			 <?php } ?>
		</table>
	
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'data_manager'); ?>
		<?php echo $form->dropDownList($model,'data_manager',array('0'=>'No','1'=>'Yes')); ?>
	</div>
	
	<div>
		<strong>Terms and conditions</strong><br />
		By using TERN DOI service you are adhering to following terms of use:
		<ul>
			<li>you will not share your app ID with others.</li>
			<li>storage and access to the material will be long-term and managed by the Facility.</li>
			<li>Mint DOI only to the material which already does not have a DOI.</li>
			<li>familiar with the Policy on DOIs: <a href="http://www.doi.org/handbook_2000/policies.html" target="_new">http://www.doi.org/handbook_2000/policies.html</a></li>
		</ul>
		<?php echo CHtml::checkBox('accept',false);?> Agree
	</div>
	
	<div class="row buttons">
		<?php
			$htmlOption = array(
				'onclick'=>"if (getElementById('accept').checked == false) alert('You need too agree the terms and conditions.'); else document.createUser-form.submit() ;",
			);
		?>
		<?php echo CHtml::button('Register', $htmlOption); ?>

	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->

protected/views/site/emailsend.php
<h>An email has been sent to the administrator for approval</h>

protected/views/site/error.php
<?php
$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<!--h2>Error <?php echo $code; ?></h2-->

<div class="error">
<h2><?php echo CHtml::encode($message); ?></h2>
</div>

protected/views/site/index.php
<?php $this->pageTitle=Yii::app()->name; ?>

<h1>Welcome to <?php echo CHtml::encode(Yii::app()->name); ?></h1>

<p>Please login to use the DOI service</p>

protected/views/site/individualuser.php
<h1>Existing DOIs</h1>

<div>
<?php echo CHtml::link('Request new DOI',Yii::app()->homeUrl.'?r=doc/create');?>
</div>

<?php

 $dataProvider = new CActiveDataProvider('Doc',array(
                    'criteria' => array(
                            'condition'=> 'user_id=:user_val ',
                              'params'=> array(':user_val' =>$model->user_id)
                        ),
                
                    )
                 );
  $this->renderPartial('../doc/_admin', array(
   'dataProvider' => $dataProvider
                       
                        )
  );

?>

protected/views/site/login.php
<?php
$this->pageTitle=Yii::app()->name . ' - Login';
$this->breadcrumbs=array(
	'Login',
);
?>

<h1>Login</h1>

<p>Please fill out the following form with your login credentials:</p>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<div class="row">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
		<p class="hint">
			Hint: You may login with <tt>demo/demo</tt> or <tt>admin/admin</tt>.
		</p>
	</div>

	<div class="row rememberMe">
		<?php echo $form->checkBox($model,'rememberMe'); ?>
		<?php echo $form->label($model,'rememberMe'); ?>
		<?php echo $form->error($model,'rememberMe'); ?>
	</div>
	
	<div class="row buttons">
		<?php echo CHtml::submitButton('Login'); ?>		

	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->

protected/views/site/loginoption.php
<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'googlelogin',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	
	
	<div class="row buttons">
		<a href="aaf">Login using AAFaa</a>		
	</div>
	<div class="row buttons">
		<?php echo CHtml::link('Login using Google',array('site/google')); ?>		
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->
    

protected/views/site/notadmin.php
<h2>You are not allow to perform this action.</h2>

protected/views/site/notapproved.php
<h2>Your account will be verified and approved by our administrator.</h2>

protected/views/site/notenabled.php
<h2>Your account is disabled by the administrator.</h2>